import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import ReactQueryProvider from '@/components/providers/ReactQueryProvider'
import { Toaster } from '@/components/ui/sonner'
import NextTopLoader from 'nextjs-toploader'

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-manrope',
})

export const metadata: Metadata = {
  title: 'Home Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <NextTopLoader color="#061F3D" height={3} showSpinner={false} />
        <ReactQueryProvider>
          <Providers>
            {children}
            <Toaster position="bottom-right" />
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
